/**
 * "Open commit dialog" IPC — finds VCS working copies for a project (walk up
 * for ancestor .git/.svn, walk down for nested ones used as submodules /
 * svn:externals), generates a simple auto-message from `git status` / `svn
 * status`, then launches TortoiseGit / TortoiseSVN commit dialogs.
 *
 * NEVER auto-commits — only opens dialogs. Same contract as the /commit-git
 * and /commit-svn slash skills: the user reviews and clicks OK in
 * TortoiseProc.
 */

import { registerHandler } from '../shared/typed-ipc'
import { getAgent } from '../../../core/agents/index.js'
import { getAppConfig } from './ipc-windows'
import { DEFAULT_AGENT_ID } from '../../../core/types/contracts.js'
import { existsSync, readdirSync, statSync, writeFileSync } from 'fs'
import { isAbsolute, join, sep, resolve } from 'path'
import { spawn, spawnSync } from 'child_process'
import { tmpdir, homedir } from 'os'
import { logError } from './logger'
import { findFirstAncestorWithMarker, findTopmostSvnAncestor } from '../../../core/menu-core/file-diff-vcs.js'
import type { AiModel, CommitOptions, CommitResult, CommitVcs as Vcs, CommitVcsRequest as VcsRequest } from '../../../core/types/ipc-contracts.js'

const ALL_VCS: Vcs[] = ['git', 'svn', 'hg']

const AI_PROMPT = [
  'Generate a commit message for the diff piped on stdin.',
  '',
  'Format:',
  '- First line: imperative title (under 72 chars), no trailing period.',
  '- Blank line.',
  '- Bulleted change list using `-`, one bullet per logical change (group related files together).',
  '- Each bullet should name specific features / components / APIs touched — not "update X".',
  '- Keep total under ~10 bullets; merge minor related items into one bullet.',
  '',
  'Rules:',
  '- No AI attribution, no "Generated by", no emoji.',
  '- Skip version-bump noise (package.json `version` field only).',
  '- Skip whitespace-only or trivial formatting changes.',
  '- Plain text — no markdown headers, no code fences around the message itself.',
  '',
  'Output only the commit message body. Nothing else.',
].join('\n')

const AI_TIMEOUT_MS = 60_000
// Cap the diff we send to the model. Smaller diff = faster inference + lower
// cost. 50KB is plenty for ~600-1200 lines of meaningful change — bigger
// commits are rare for our workflow and the model still gets enough context
// from the truncated head.
const AI_DIFF_MAX_BYTES = 50_000

const SKIP_DIRS = new Set([
  'node_modules', 'dist', 'out', 'build', '.next', '.vite',
  '__pycache__', '.cache', 'coverage', '.idea', '.vscode',
])

const TORTOISE_GIT_EXE = 'C:\\Program Files\\TortoiseGit\\bin\\TortoiseGitProc.exe'
const TORTOISE_SVN_EXE = 'C:\\Program Files\\TortoiseSVN\\bin\\TortoiseProc.exe'
const TORTOISE_HG_EXE = 'C:\\Program Files\\TortoiseHg\\thg.exe'

function markerForVcs(vcs: Vcs): '.git' | '.svn' | '.hg' {
  return vcs === 'git' ? '.git' : vcs === 'svn' ? '.svn' : '.hg'
}

// ────────────────────────────────────────────────────────────────────────────
// Discovery — walk up + down for VCS markers
// ────────────────────────────────────────────────────────────────────────────

function walkDownForMarkers(startDir: string, marker: '.git' | '.svn' | '.hg', maxDepth = 6): string[] {
  const out: string[] = []
  let visited = 0
  const visit = (dir: string, depth: number) => {
    // maxDepth + a hard visit cap: a scratch session's cwd is the home dir, and the 5s
    // commit-vcs probe would otherwise descend the whole home tree (incl. AppData) 3×.
    if (depth > maxDepth || ++visited > 4000) return
    // If THIS dir holds the marker, record it as a root and stop descending
    // (we don't want nested .git inside another .git's worktree).
    if (existsSync(`${dir}${sep}${marker}`)) {
      out.push(dir)
      return
    }
    let entries: import('fs').Dirent[]
    try {
      entries = readdirSync(dir, { withFileTypes: true })
    } catch {
      return
    }
    for (const e of entries) {
      if (!e.isDirectory()) continue
      if (e.name.startsWith('.')) continue
      if (SKIP_DIRS.has(e.name)) continue
      visit(`${dir}${sep}${e.name}`, depth + 1)
    }
  }
  // Skip the very-top dir itself (caller already handles "walk up" for that)
  // — only true descendants.
  let entries: import('fs').Dirent[]
  try {
    entries = readdirSync(startDir, { withFileTypes: true })
  } catch {
    return []
  }
  for (const e of entries) {
    if (!e.isDirectory()) continue
    if (e.name.startsWith('.')) continue
    if (SKIP_DIRS.has(e.name)) continue
    visit(`${startDir}${sep}${e.name}`, 1)
  }
  return out
}

function findVcsRoots(projectDir: string, vcs: Vcs): string[] {
  if (!isAbsolute(projectDir)) return []
  try {
    if (!statSync(projectDir).isDirectory()) return []
  } catch {
    return []
  }
  const marker = markerForVcs(vcs)
  const set = new Set<string>()
  // SVN keeps `.svn` either at WC root only (modern) or in every subdir
  // (legacy 1.6); walk all the way up to the topmost ancestor for safety.
  // Git and Mercurial use a single `.git`/`.hg` at the repo root.
  const ancestor = vcs === 'svn' ? findTopmostSvnAncestor(projectDir) : findFirstAncestorWithMarker(projectDir, marker)
  if (ancestor) set.add(ancestor)
  for (const inner of walkDownForMarkers(projectDir, marker)) set.add(inner)
  return [...set]
}

// ────────────────────────────────────────────────────────────────────────────
// Status + auto-message
// ────────────────────────────────────────────────────────────────────────────

/**
 * Get the full diff text for the LLM. Truncates very large diffs because
 * Claude's CLI can't accept unbounded stdin and large diffs blow up costs.
 * For git: `git diff HEAD` (working tree vs last commit). For svn: scoped
 * `svn diff <path>` if we have a scope, else full `svn diff`.
 */
function runDiff(vcs: Vcs, repoRoot: string, scope?: string): string {
  let raw = ''
  if (vcs === 'git') {
    const r = spawnSync('git', ['-C', repoRoot, 'diff', 'HEAD'], {
      encoding: 'utf-8',
      timeout: 15_000,
      windowsHide: true,
      maxBuffer: 32 * 1024 * 1024,
    })
    raw = r.stdout ?? ''
  } else if (vcs === 'hg') {
    const r = spawnSync('hg', ['diff'], {
      encoding: 'utf-8',
      timeout: 15_000,
      cwd: repoRoot,
      windowsHide: true,
      maxBuffer: 32 * 1024 * 1024,
    })
    raw = r.stdout ?? ''
  } else {
    const args = ['diff']
    if (scope) args.push(scope)
    const r = spawnSync('svn', args, {
      encoding: 'utf-8',
      timeout: 15_000,
      cwd: repoRoot,
      windowsHide: true,
      maxBuffer: 32 * 1024 * 1024,
    })
    raw = r.stdout ?? ''
  }
  if (raw.length > AI_DIFF_MAX_BYTES) {
    raw = raw.slice(0, AI_DIFF_MAX_BYTES) + `\n\n[... diff truncated at ${AI_DIFF_MAX_BYTES} bytes; ${(raw.length / 1024).toFixed(0)}KB total ...]`
  }
  return raw
}

/**
 * Run `claude -p` with the diff piped on stdin and the AI_PROMPT as the
 * user prompt. Returns the model's commit message text, or null on timeout
 * / non-zero exit / empty output. Falls back to the basic auto-message
 * upstream when null is returned.
 */
function generateAiMessage(model: AiModel, repoRoot: string, diff: string): Promise<{ msg: string | null; elapsedMs: number }> {
  return new Promise((resolve) => {
    if (model === 'off' || !diff) {
      resolve({ msg: null, elapsedMs: 0 })
      return
    }
    const t0 = Date.now()
    // Run from the OS temp dir (not the repo) so the agent doesn't load
    // the project's CLAUDE.md / AGENTS.md / skills on startup — those add
    // a few seconds to the first invocation. The user's global config
    // still loads, but it's the per-project context that's slow.
    //
    // Build the exec command via the agent adapter. Reads the per-config
    // defaultAgent so a user who switches to Codex (once shipped) routes
    // commit summarization through the new backend without code changes.
    // Wrapped in try/catch because a stub adapter throws on the spawn
    // path — fall through to the basic auto-message path on failure.
    const agentId = getAppConfig()?.defaultAgent ?? DEFAULT_AGENT_ID
    let exec
    try {
      // plan mode = text-only, no tool execution. The diff piped on stdin
      // is attacker-controlled (malicious repo / coworker branch); without
      // this a prompt-injected diff could drive Bash etc. under the user's
      // global permission profile. Plan mode neutralizes that.
      exec = getAgent(agentId).buildExecCommand(AI_PROMPT, model, { ephemeral: true, permissionMode: 'plan' })
    } catch (err) {
      // A stub adapter (Codex) throws on the spawn path. Resolve null so
      // the caller falls through to the basic auto-message + dialog
      // instead of rejecting (which would skip the dialog entirely).
      // `resolve` directly — `finish` isn't defined yet at this point.
      logError('commit', `AI summary unavailable: ${String(err)}`)
      resolve({ msg: null, elapsedMs: Date.now() - t0 })
      return
    }
    const proc = spawn(exec.command, exec.args, {
      cwd: tmpdir(),
      stdio: ['pipe', 'pipe', 'pipe'],
      windowsHide: true,
    })
    let stdout = ''
    let stderr = ''
    let settled = false
    const finish = (msg: string | null) => {
      if (settled) return
      settled = true
      resolve({ msg, elapsedMs: Date.now() - t0 })
    }
    const timer = setTimeout(() => {
      try { proc.kill() } catch {}
      logError('commit', `${exec.command} ${model} timed out after ${AI_TIMEOUT_MS}ms`)
      finish(null)
    }, AI_TIMEOUT_MS)
    proc.stdout.on('data', (d) => { stdout += d.toString('utf-8') })
    proc.stderr.on('data', (d) => { stderr += d.toString('utf-8') })
    proc.on('close', (code) => {
      clearTimeout(timer)
      if (code !== 0) {
        logError('commit', `${exec.command} ${model} exit ${code}: ${stderr.slice(0, 400)}`)
        finish(null)
        return
      }
      const trimmed = stdout.trim()
      finish(trimmed.length > 0 ? trimmed : null)
    })
    proc.on('error', (err) => {
      clearTimeout(timer)
      logError('commit', `${exec.command} ${model} spawn error: ${err.message}`)
      finish(null)
    })
    proc.stdin.end(diff, 'utf-8')
  })
}

function runStatus(vcs: Vcs, repoRoot: string, scope?: string): { lines: string[]; raw: string } {
  if (vcs === 'git') {
    const r = spawnSync('git', ['-C', repoRoot, 'status', '--porcelain'], {
      encoding: 'utf-8',
      timeout: 10_000,
      windowsHide: true,
      maxBuffer: 10 * 1024 * 1024,
    })
    const raw = r.stdout ?? ''
    return { lines: raw.split(/\r?\n/).filter(Boolean), raw }
  }
  if (vcs === 'hg') {
    // Mercurial porcelain-like status: `M file`, `A file`, `R file`, `? file`.
    // We keep `?` (untracked) lines — TortoiseHg's commit dialog surfaces
    // them with checkboxes so the user can add+commit in one step. Filtering
    // them out would make a freshly-init'd repo always look "clean" and
    // never open the dialog. Add a `.hgignore` to silence noise.
    const r = spawnSync('hg', ['status'], {
      encoding: 'utf-8',
      timeout: 10_000,
      cwd: repoRoot,
      windowsHide: true,
      maxBuffer: 10 * 1024 * 1024,
    })
    const raw = r.stdout ?? ''
    return { lines: raw.split(/\r?\n/).filter(Boolean), raw }
  }
  const args = ['status']
  if (scope) args.push(scope)
  const r = spawnSync('svn', args, {
    encoding: 'utf-8',
    timeout: 10_000,
    cwd: repoRoot,
    windowsHide: true,
    maxBuffer: 10 * 1024 * 1024,
  })
  const raw = r.stdout ?? ''
  // Drop externals-marker (`X       ...`) lines — they're informational, not
  // commitable here.
  const lines = raw.split(/\r?\n/).filter((l) => l && !l.startsWith('X'))
  return { lines, raw }
}

/**
 * Auto-generate a starter commit message from the status output. Doesn't aim
 * for high-quality summarization (no LLM here — see header doc); user can
 * (and should) refine it in the TortoiseProc dialog before committing.
 *
 * Lines look like:
 *   git:  ` M path/to/file`   (porcelain XY column)
 *   svn:  `M       path/to/file`
 */
function autoMessage(vcs: Vcs, lines: string[]): string {
  if (lines.length === 0) return '(no changes)'
  const buckets = { add: [] as string[], mod: [] as string[], del: [] as string[], other: [] as string[] }
  for (const line of lines) {
    // git porcelain: 2-char XY column at position 0, then space, then path.
    // svn:           1-char code at position 0, padded to 8 chars, then path.
    // hg:            1-char code at position 0, space, then path.
    let code: string
    let pathPart: string
    if (vcs === 'git') {
      code = line.slice(0, 2).trim()
      pathPart = line.slice(3)
    } else if (vcs === 'hg') {
      code = line.slice(0, 1)
      pathPart = line.slice(2).trim()
    } else {
      code = line.slice(0, 1)
      pathPart = line.slice(8).trim()
    }
    const name = pathPart.split(/[/\\]/).pop() ?? pathPart
    if (code === 'A' || code === '??' || code === '?') buckets.add.push(name)
    else if (code === 'M' || code === 'MM') buckets.mod.push(name)
    else if (code === 'D' || code === '!' || code === 'R') buckets.del.push(name)
    else buckets.other.push(name)
  }
  const parts: string[] = []
  if (buckets.mod.length) parts.push(`Modify ${buckets.mod.length}`)
  if (buckets.add.length) parts.push(`Add ${buckets.add.length}`)
  if (buckets.del.length) parts.push(`Delete ${buckets.del.length}`)
  const summary = parts.join(', ') + (parts.length === 0 ? 'Update' : '') + ' file' + (lines.length === 1 ? '' : 's')

  const all = [...buckets.mod, ...buckets.add, ...buckets.del, ...buckets.other]
  const previewN = 12
  const preview = all.slice(0, previewN).map((n) => `- ${n}`).join('\n')
  const moreSuffix = all.length > previewN ? `\n…and ${all.length - previewN} more` : ''
  return `${summary}\n\n${preview}${moreSuffix}`
}

// ────────────────────────────────────────────────────────────────────────────
// Dialog launch
// ────────────────────────────────────────────────────────────────────────────

function safeBaseName(p: string): string {
  return p.split(/[/\\]/).filter(Boolean).pop()?.replace(/[^A-Za-z0-9._-]/g, '_') ?? 'repo'
}

function writeMsgFile(vcs: Vcs, repoRoot: string, msg: string): string {
  const file = join(tmpdir(), `commit-msg-${vcs}-${safeBaseName(repoRoot)}-${Date.now()}.txt`)
  writeFileSync(file, msg, 'utf-8')
  return file
}

function launchDialog(vcs: Vcs, repoRoot: string, scope: string | null, msgFile: string): void {
  const target = scope ?? repoRoot
  if (vcs === 'hg') {
    // TortoiseHg commit dialog. The `-l <file>` flag pre-fills the commit
    // message from a file (same idea as TortoiseSVN /logmsgfile). Path can
    // be supplied positionally to scope the dialog.
    if (!existsSync(TORTOISE_HG_EXE)) {
      throw new Error(`TortoiseHg not found at ${TORTOISE_HG_EXE}`)
    }
    spawn(TORTOISE_HG_EXE, ['commit', '-R', repoRoot, '-l', msgFile, target], {
      detached: true,
      stdio: 'ignore',
      windowsHide: true,
    }).unref()
    return
  }
  const exe = vcs === 'git' ? TORTOISE_GIT_EXE : TORTOISE_SVN_EXE
  if (!existsSync(exe)) {
    throw new Error(`${vcs === 'git' ? 'TortoiseGit' : 'TortoiseSVN'} not found at ${exe}`)
  }
  // Fire-and-forget: detach so the dialog stays open after this handler
  // returns, and we don't block the renderer.
  spawn(exe, [
    '/command:commit',
    `/path:${target}`,
    `/logmsgfile:${msgFile}`,
    '/closeonend:0',
  ], {
    detached: true,
    stdio: 'ignore',
    windowsHide: true,
  }).unref()
}

// ────────────────────────────────────────────────────────────────────────────
// IPC handler
// ────────────────────────────────────────────────────────────────────────────

function resolveModel(opts: CommitOptions | undefined): AiModel {
  const fromOpts = opts?.model
  if (fromOpts === 'haiku' || fromOpts === 'sonnet' || fromOpts === 'opus' || fromOpts === 'off') {
    return fromOpts
  }
  const env = process.env.COMMIT_MSG_MODEL
  if (env === 'haiku' || env === 'sonnet' || env === 'opus' || env === 'off') return env
  return 'off' // safe default — basic auto-message, no LLM cost / delay
}

async function processVcs(
  vcs: Vcs,
  projectDir: string,
  model: AiModel,
  opened: CommitResult['dialogs'],
  skipped: string[],
): Promise<void> {
  const roots = findVcsRoots(projectDir, vcs)
  if (roots.length === 0) {
    // For 'all' we want this to be a silent skip, not an error.
    skipped.push(`${vcs}: no working copies found`)
    return
  }
  for (const repoRoot of roots) {
    try {
      // For an ancestor SVN root (where the project is a subdir), scope
      // `svn status` and the dialog to the project subdir — we don't want
      // to surface every sibling project under the same outer .svn.
      // Require a path-separator boundary so "Q:\Foo" doesn't match
      // "Q:\FooBar" (bare startsWith would).
      const isAncestor = vcs === 'svn' && projectDir.toLowerCase().startsWith(repoRoot.toLowerCase() + sep)
      const scope = isAncestor ? projectDir : null
      const status = runStatus(vcs, repoRoot, scope ?? undefined)
      if (status.lines.length === 0) {
        skipped.push(`${vcs} ${repoRoot} (clean)`)
        continue
      }

      let msg = autoMessage(vcs, status.lines)
      let usedAi = false
      let aiMs: number | undefined

      if (model !== 'off') {
        const diff = runDiff(vcs, repoRoot, scope ?? undefined)
        if (diff) {
          const ai = await generateAiMessage(model, repoRoot, diff)
          aiMs = ai.elapsedMs
          if (ai.msg) {
            msg = ai.msg
            usedAi = true
          }
        }
      }

      const msgFile = writeMsgFile(vcs, repoRoot, msg)
      launchDialog(vcs, repoRoot, scope, msgFile)
      opened.push({ repoRoot, statusLines: status.lines.length, msgFile, usedAi, aiMs })
    } catch (err) {
      logError('commit', `${vcs} ${repoRoot}: ${err}`)
      skipped.push(`${vcs} ${repoRoot} (error: ${err instanceof Error ? err.message : String(err)})`)
    }
  }
}

export function registerCommitIpc(): void {
  // Cheap probe — used by the sidebar to hide commit buttons for VCS that
  // aren't applicable to the project. Only checks for markers, doesn't run
  // any subprocess (so it's safe to call on every panel mount).
  registerHandler('commit:detect-vcs', async (_e, projectDir: string): Promise<{ git: boolean; svn: boolean; hg: boolean }> => {
    if (!projectDir || typeof projectDir !== 'string') {
      return { git: false, svn: false, hg: false }
    }
    // A scratch session's cwd is the HOME dir; the side-panel commit-vcs probe runs this every
    // 5s and walkDownForMarkers would scan the whole home tree 3× (git/svn/hg). Home is never a
    // working copy you'd commit — skip it (the entry cap in walkDownForMarkers covers other trees).
    try { if (resolve(projectDir) === resolve(homedir())) return { git: false, svn: false, hg: false } } catch { /* fall through */ }
    return {
      git: findVcsRoots(projectDir, 'git').length > 0,
      svn: findVcsRoots(projectDir, 'svn').length > 0,
      hg: findVcsRoots(projectDir, 'hg').length > 0,
    }
  })

  registerHandler('commit:open-dialog', async (_e, vcs, projectDir, opts) => {
    if (vcs !== 'git' && vcs !== 'svn' && vcs !== 'hg' && vcs !== 'all') {
      return { ok: false, vcs, dialogs: [], skipped: [], error: `invalid vcs: ${vcs}` }
    }
    if (!projectDir || typeof projectDir !== 'string') {
      return { ok: false, vcs, dialogs: [], skipped: [], error: 'invalid projectDir' }
    }

    const model = resolveModel(opts)
    const opened: CommitResult['dialogs'] = []
    const skipped: string[] = []
    const vcsList: Vcs[] = vcs === 'all' ? ALL_VCS : [vcs]

    // Parallel — each VCS gets its own `claude -p` call and dialog launch.
    // Dialogs are detached spawns (fire-and-forget), so all of them surface
    // at once without waiting for the user to close the previous one. For
    // single-VCS requests Promise.all has the same effect as a serial await.
    await Promise.all(vcsList.map((v) => processVcs(v, projectDir, model, opened, skipped)))

    return { ok: opened.length > 0, vcs, dialogs: opened, skipped }
  })

  // History viewer — launches the relevant Tortoise log dialog. Read-only,
  // no msg-file or commit machinery; just an external-tool spawn keyed by
  // VCS. Mirrors the binary-location and detach pattern from launchDialog.
  registerHandler('commit:open-log', async (_e, vcs, projectDir) => {
    if (vcs !== 'git' && vcs !== 'svn' && vcs !== 'hg') {
      return { ok: false, error: `invalid vcs: ${vcs}` }
    }
    if (!projectDir || typeof projectDir !== 'string') {
      return { ok: false, error: 'invalid projectDir' }
    }
    const roots = findVcsRoots(projectDir, vcs)
    if (roots.length === 0) {
      return { ok: false, error: `no ${vcs} working copy found for ${projectDir}` }
    }
    const repoRoot = roots[0]
    const binary =
      vcs === 'git' ? 'C:\\Program Files\\TortoiseGit\\bin\\TortoiseGitProc.exe'
      : vcs === 'svn' ? 'C:\\Program Files\\TortoiseSVN\\bin\\TortoiseProc.exe'
      : 'C:\\Program Files\\TortoiseHg\\thg.exe'
    if (!existsSync(binary)) {
      return { ok: false, error: `${binary} not found — install the corresponding Tortoise tool` }
    }
    const args = vcs === 'hg'
      ? ['log', repoRoot]
      : ['/command:log', `/path:${repoRoot}`]
    try {
      const child = spawn(binary, args, { detached: true, stdio: 'ignore', windowsHide: true })
      child.unref()
      return { ok: true }
    } catch (err) {
      const msg = String(err)
      logError('commit:open-log', msg)
      return { ok: false, error: msg }
    }
  })
}
