/**
 * Remote App Control — client side. All calls to a peer go through the main
 * process (so the bearer token is attached server-side and there is no browser
 * CORS surface). HTTP for probe / windows / open-tab / launch; a `ws` client
 * for the live tab stream, whose frames are bridged to the calling renderer via
 * the `remote:stream-frame` event and whose keystrokes come back over
 * `remote:stream-send-keys`.
 */

import http from 'node:http'
import { hostname } from 'node:os'
import { ipcMain, type WebContents } from 'electron'
import { WebSocket } from 'ws'
import { registerHandler, registerSend } from '../shared/typed-ipc'
import { publishTo } from './streams'
import { recordRemoteActivity } from './remote-activity'
import { REMOTE_PROTOCOL } from '../../../core/types/remote-control.js'
import type { RemotePeer, PeerProbeResult } from '../../../core/types/remote-control.js'

const REQ_TIMEOUT = 4000

function httpJson(
  host: string,
  port: number,
  method: 'GET' | 'POST',
  pathname: string,
  token?: string,
  body?: unknown,
  timeoutMs: number = REQ_TIMEOUT,
): Promise<any> {
  return new Promise((resolve, reject) => {
    const data = body !== undefined ? JSON.stringify(body) : undefined
    const req = http.request(
      {
        host,
        port,
        method,
        path: pathname,
        timeout: timeoutMs,
        headers: {
          ...(token ? { Authorization: `Bearer ${token}` } : {}),
          // Label this controller in the peer's Remote Activity Log (advisory, not auth).
          'X-Remote-Machine': hostname(),
          ...(data ? { 'Content-Type': 'application/json', 'Content-Length': Buffer.byteLength(data) } : {}),
        },
      },
      (res) => {
        let buf = ''
        res.on('data', (c) => { buf += c })
        res.on('end', () => {
          let parsed: any = {}
          try { parsed = buf ? JSON.parse(buf) : {} } catch { /* leave {} */ }
          if ((res.statusCode ?? 0) >= 400) {
            // Attach the HTTP status so callers can tell an auth rejection (401/403 — the peer IS up)
            // from an unreachable/transient failure. The message stays the peer's `error` when present.
            const err = new Error(parsed?.error ? String(parsed.error) : `HTTP ${res.statusCode}`) as Error & { status?: number }
            err.status = res.statusCode
            reject(err)
          } else {
            resolve(parsed)
          }
        })
      },
    )
    req.on('error', reject)
    req.on('timeout', () => req.destroy(new Error('timeout')))
    if (data) req.write(data)
    req.end()
  })
}

const PROBE_HEALTH_TIMEOUT = 2500 // shorter than REQ_TIMEOUT: 2 attempts (~5s) fit the 5s probe loop

async function probe(peer: RemotePeer): Promise<PeerProbeResult> {
  // app-up = the control-server answers /control/health (token-gated). Try twice: a lone transient
  // failure (timeout/reset) shouldn't demote an up peer to "app closed" and flap the status. A
  // 401/403 is DEFINITIVE (the server answered, it just rejected our token) → report it as such and
  // stop — no retry, no agent fallback.
  for (let attempt = 0; attempt < 2; attempt++) {
    try {
      const ctrl = await httpJson(peer.host, peer.controlPort, 'GET', '/control/health', peer.token, undefined, PROBE_HEALTH_TIMEOUT)
      if (ctrl?.ok) {
        // A legacy v1 app answers health but has no protocol field → undefined → incompatible.
        const protocol = typeof ctrl.protocol === 'number' ? ctrl.protocol : undefined
        return { reachability: 'app-up', hostname: ctrl.hostname, version: ctrl.version, app: ctrl.app, protocol, compatible: protocol === REMOTE_PROTOCOL }
      }
      break // 2xx but no `ok` — odd; treat as not-app-up, don't retry
    } catch (e: any) {
      const status = e?.status as number | undefined
      if (status === 401 || status === 403) return { reachability: 'unauthorized', error: 'invalid token' }
      // else transient (timeout / reset / connection refused) — retry once, then fall to the agent.
    }
  }
  // agent-only = the always-on agent answers its unauth /api/health.
  try {
    const agent = await httpJson(peer.host, peer.agentPort, 'GET', '/api/health')
    if (agent?.ok) return { reachability: 'agent-only' }
  } catch { /* offline */ }
  return { reachability: 'offline' }
}

// ── live WS streams (one per open viewer) ────────────────────────────────────
// `streamId` is generated by the RENDERER and passed in, so the renderer can
// attach its `remote:stream-frame` listener BEFORE opening (no dropped snapshot,
// no wrong-PTY routing). Streams are tracked per `webContents.id` so closing /
// reloading the controller window tears down its sockets (no orphan leak).
const streams = new Map<string, { ws: WebSocket; wcId: number }>()
const hookedWc = new Set<number>()

function cleanupWc(wcId: number): void {
  for (const [id, s] of streams) {
    if (s.wcId === wcId) { try { s.ws.close() } catch { /* ignore */ } streams.delete(id) }
  }
}

function hookWc(wc: WebContents): void {
  if (hookedWc.has(wc.id)) return
  hookedWc.add(wc.id)
  const wcId = wc.id
  wc.once('destroyed', () => { cleanupWc(wcId); hookedWc.delete(wcId) })
  // A reload / top-level navigation drops the renderer's listeners without a
  // 'destroyed' event — close that window's streams so they don't orphan.
  ;(wc as any).on('did-start-navigation', (_e: unknown, _url: string, isInPlace: boolean, isMainFrame: boolean) => {
    if (isMainFrame && !isInPlace) cleanupWc(wcId)
  })
}

function streamOpen(peer: RemotePeer, terminalId: string, streamId: string, wc: WebContents): { ok: boolean; error?: string } {
  try {
    hookWc(wc)
    const ws = new WebSocket(`ws://${peer.host}:${peer.controlPort}`, {
      headers: { Authorization: `Bearer ${peer.token}`, 'X-Remote-Machine': hostname() },
    })
    streams.set(streamId, { ws, wcId: wc.id })
    const machine = peer.name || peer.host
    // Connect deadline: a peer that accepts TCP but stalls the WS upgrade would
    // otherwise leave a blank viewer for minutes. terminate() fires 'close' →
    // the renderer gets an exit frame and shows "stream ended".
    const connectTimer = setTimeout(() => {
      if (ws.readyState !== ws.OPEN) { try { ws.terminate() } catch { /* ignore */ } }
    }, 5000)
    ws.on('open', () => {
      clearTimeout(connectTimer)
      try { ws.send(JSON.stringify({ type: 'subscribe', terminalId })) } catch { /* ignore */ }
      recordRemoteActivity({
        ts: Date.now(), side: 'controller', via: 'human', machine, action: 'view-start',
        target: terminalId, message: `started viewing ${terminalId} on ${machine}`,
      })
    })
    ws.on('message', (raw) => {
      let msg: any
      try { msg = JSON.parse(raw.toString()) } catch { return }
      if (!wc.isDestroyed()) publishTo(wc, 'remote:stream-frame', streamId, msg)
    })
    ws.on('close', () => {
      clearTimeout(connectTimer)
      if (!wc.isDestroyed()) publishTo(wc, 'remote:stream-frame', streamId, { type: 'exit' })
      streams.delete(streamId)
      recordRemoteActivity({
        ts: Date.now(), side: 'controller', via: 'human', machine, action: 'view-stop',
        target: terminalId, message: `stopped viewing ${terminalId} on ${machine}`,
      })
    })
    ws.on('error', (e) => {
      if (!wc.isDestroyed()) publishTo(wc, 'remote:stream-frame', streamId, { type: 'error', message: String((e as Error).message ?? e) })
    })
    return { ok: true }
  } catch (e: any) {
    return { ok: false, error: String(e?.message ?? e) }
  }
}

export function registerRemoteClientIpc(): void {
  registerHandler('remote:probe', async (_e, peer) => probe(peer))

  registerHandler('remote:windows', async (_e, peer) => {
    try {
      const r = await httpJson(peer.host, peer.controlPort, 'POST', '/control/windows', peer.token, {})
      return { ok: true, windows: r.windows ?? [], version: r.version }
    } catch (e: any) {
      return { ok: false, error: String(e?.message ?? e) }
    }
  })

  registerHandler('remote:open-tab', async (_e, peer, req) => {
    try {
      await httpJson(peer.host, peer.controlPort, 'POST', '/control/open-tab', peer.token, req)
      const machine = peer.name || peer.host
      recordRemoteActivity({
        ts: Date.now(), side: 'controller', via: 'human', machine, action: 'open-tab',
        target: req.terminalId ?? req.tabType,
        message: `open-tab (${req.tabType}${req.terminalId ? ` → ${req.terminalId}` : ''}) on ${machine}`,
      })
      return { ok: true }
    } catch (e: any) {
      return { ok: false, error: String(e?.message ?? e) }
    }
  })

  registerHandler('remote:close-tab', async (_e, peer, terminalId) => {
    try {
      await httpJson(peer.host, peer.controlPort, 'POST', '/control/close-tab', peer.token, { terminalId })
      const machine = peer.name || peer.host
      recordRemoteActivity({
        ts: Date.now(), side: 'controller', via: 'human', machine, action: 'close-tab',
        target: terminalId, message: `close-tab (${terminalId}) on ${machine}`,
      })
      return { ok: true }
    } catch (e: any) {
      return { ok: false, error: String(e?.message ?? e) }
    }
  })

  registerHandler('remote:launch-app', async (_e, peer) => {
    try {
      await httpJson(peer.host, peer.agentPort, 'POST', '/api/launch-app', peer.token, {})
      return { ok: true }
    } catch (e: any) {
      return { ok: false, error: String(e?.message ?? e) }
    }
  })

  // Generic op passthrough → a peer's reach-gated /op. The peer enforces reach (only
  // control + debug ops accept `via:'remote'`), so this can't drive anything it wouldn't
  // already expose. Returns the op's `data` on success, else { ok:false, error }.
  registerHandler('remote:op', async (_e, peer, name, args) => {
    try {
      const r = await httpJson(peer.host, peer.controlPort, 'POST', '/op', peer.token, { name, args: args ?? [] })
      return { ok: true, data: (r as { data?: unknown })?.data }
    } catch (e: any) {
      return { ok: false, error: String(e?.message ?? e) }
    }
  })

  registerHandler('remote:stream-open', async (e, peer, terminalId, streamId) => streamOpen(peer, terminalId, streamId, e.sender))

  registerSend('remote:stream-send-keys', (_e, streamId: string, data: string) => {
    const s = streams.get(streamId)
    if (s && s.ws.readyState === s.ws.OPEN) {
      try { s.ws.send(JSON.stringify({ type: 'keys', data })) } catch { /* ignore */ }
    }
  })

  registerSend('remote:stream-close', (_e, streamId: string) => {
    const s = streams.get(streamId)
    if (s) { try { s.ws.close() } catch { /* ignore */ } streams.delete(streamId) }
  })
}
